### ISSUE TITLE
Upgrade workspace reqwest 0.12 -> 0.13 for direct-API agent backend

### ISSUE THREAD

**Issue by geoffjay** [geoffjay/agentd#1115]
## Context

The direct-API agent backend (#899) requires either `claudius` or `claude-agent`, both
of which depend on reqwest 0.13. The agentd workspace currently uses reqwest 0.12 across
14 crates. This issue tracks the upgrade.

## Parent
- #899 (Epic: Custom agent via Claude Agent SDK)
- Prerequisite for #900 (Phase 1: Research & Prototyping)

### Current state
- Workspace spec: `reqwest = { version = "0.12", ... }` in root `Cargo.toml`
- Resolved version: `reqwest v0.12.28`
- Used in 14 crates, all with basic `Client` + JSON usage patterns
- No advanced reqwest features (no custom TLS config, no multipart, no proxies)

### Breaking changes in 0.13
- Compression features (brotli, deflate, gzip, zstd) now use `tower-http` instead of `async-compression`
- TLS: rustls features simplified, `__rustls-ring` removed, consolidated to `__rustls-aws-lc-rs`
- `form` and `query` features now depend on `serde_urlencoded`
- Core `Client` API (`.get()`, `.post()`, `.json()`, `.send()`) is **unchanged**

### axum compatibility
- axum 0.8 lists reqwest 0.12 as an optional dependency
- agentd does not use axum's reqwest feature
- Dual reqwest versions (0.12 for axum internals, 0.13 for agent backend) can coexist
- Alternatively, axum may work fine with 0.13 since it's optional and not in the public API

## Tasks
- [ ] Update root `Cargo.toml`: `reqwest = { version = "0.13", ... }`
- [ ] Update feature flags if needed:
  - Check `rustls-tls` feature name (may have changed)
  - Check if `json` feature is still the same
- [ ] Update any crate-level `Cargo.toml` that pins reqwest directly (not via workspace)
- [ ] Run `cargo build` -- fix any compilation errors
- [ ] Run `cargo test` -- verify no regressions
- [ ] Run `cargo clippy` -- clean up any new warnings
- [ ] Verify all services start correctly

## Affected Crates
```
crates/ask/Cargo.toml
crates/baml/Cargo.toml
crates/cli/Cargo.toml
crates/common/Cargo.toml
crates/communicate/Cargo.toml
crates/hook/Cargo.toml
crates/index/Cargo.toml
crates/mcp/Cargo.toml
crates/memory/Cargo.toml
crates/monitor/Cargo.toml
crates/notify/Cargo.toml
crates/orchestrator/Cargo.toml
crates/ui/Cargo.toml
crates/wrap/Cargo.toml
```

## Risk Assessment
**Low risk.** All 14 crates use `reqwest::Client` for basic HTTP + JSON. No custom TLS
configuration, no streaming bodies, no multipart uploads. The core client API is stable
across 0.12 -> 0.13.

## Stack Base
Branch off `feature/autonomous-pipeline` and PR back into it.
